### ISSUE TITLE
Please add benchmark results

### ISSUE THREAD

**Issue by loic-sharma** [zivkan/Benchmarks#1]
This project is cool! I'd love to see what benchmarks' results in a markdown file or something :)

**Comment by zivkan** [comment]
I added a readme and results for the semantic versioning benchmark I pushed a few days ago. I plan on doing more work on the nuget.org catalog parser benchmarks, so I'll add results when I do that work, and try to remember to add results for anything new I add.  Also keep an eye out on my blog, where I'll be discussing the results, when I feel I understand it well enough to write about: https://www.zivkan.com/
